pipeline:
  build:	  
    image: maven:3-jdk-8
    commands: 
      - "mvn package -B"
      - "mvn cobertura:cobertura"
      
  codeCoverage-sonarQube:
    image: aosapps/drone-sonar-plugin:0.8
    quality: OK
    secrets: [ sonar_host, sonar_token ] 
    
  coverage-report:
    image: plugins/codecov
    environment:
      CODECOV_TOKEN: 918e08be-96db-436f-8cb8-758a9865c462
    commands:
      - "curl -s https://codecov.io/bash -v"
